log_level: info
access_log:
http:
  servers:
    - name: site2
      listen: ":9002"
      proxy_pass: https://httpbin.org
      proxy_path: /get
      request_headers:
        - Authentication: Basic 123456
        - Yomama: Pk
      domains: [localhost]
      root: /web
