log_level: info
access_log:
http:
  servers:
    - name: site
      listen: ":9002"
      proxies:
        - proxy_pass: https://httpbin.org
          proxy_path: /get
          request_headers:
            - Authentication: Basic 123456
            - Yomama: Pk
        - proxy_pass: https://postman-echo.com
          proxy_path: /headers
          request_headers:
            - Authentication: Basic 11235453
      domains: [localhost]
      root: /web
